DevProject/Models/JobPoster.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class JobPoster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPoster()
        {
            this.Applies = new HashSet<Apply>();
        }
    
        public int JobPostID { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [MaxLength(20, ErrorMessage = "Max 20 Characters Allowed")]
        [MinLength(6, ErrorMessage = "Password must be at least 6 characters ")]
        public string UserPass { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Compare("UserPass", ErrorMessage = "Passwords Mismatch,Please Re-Enter")]
        [Display(Name = "Confirm Password")]
        public string ConfirmPass { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public string JobName { get; set; }
        public string JobDesc { get; set; }
        public short WorkDays { get; set; }
        public long Salary { get; set; }
        public string Skills { get; set; }
        public Nullable<short> Age { get; set; }
        public string Gender { get; set; }
        
        public long ConNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apply> Applies { get; set; }

        //public static implicit operator int(JobPoster v)
        //{
        //    throw new NotImplementedException();
        //}
    }
}

DevProject/Controllers/JobFindersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DevProject.Models;

namespace DevProject.Controllers
{
    public class JobFindersController : Controller
    {
        private DevProjectDbEntities db = new DevProjectDbEntities();

        // GET: JobFinders
        public ActionResult Index()
        {
            return View(db.JobFinders.ToList());
        }

        // GET: JobFinders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobFinder jobFinder = db.JobFinders.Find(id);
            if (jobFinder == null)
            {
                return HttpNotFound();
            }
            return View(jobFinder);
        }

        // GET: JobFinders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: JobFinders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobFindID,UserName,UserPass,ConfirmPass,Address,UserEmail,ConNumber,College,University,Experience,Resume")] JobFinder jobFinder )
        {
            //string filepath = Server.MapPath("~/Content/Hi.docx");
            //string filename = Path.GetFileName(filepath);
            //FileStream fs = new FileStream(filepath, FileMode.Open, FileAccess.Read);
            //BinaryReader br = new BinaryReader(fs);
            //byte[] bytes = br.ReadBytes((Int32)fs.Length);
            if (ModelState.IsValid)
            {
                db.JobFinders.Add(jobFinder);
                db.SaveChanges();
                return RedirectToAction("Login");
            }

            return View(jobFinder);
        }

        // GET: JobFinders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobFinder jobFinder = db.JobFinders.Find(id);
            if (jobFinder == null)
            {
                return HttpNotFound();
            }
            return View(jobFinder);
        }

        // POST: JobFinders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobFindID,UserName,UserPass,Address,UserEmail,ConNumber,College,University,Experience,Resume")] JobFinder jobFinder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jobFinder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(jobFinder);
        }


        //GET: Login

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(TempUser tempUser)
        {
            if (ModelState.IsValid)
            {
                var user = db.JobFinders.Where(u => u.UserName.Equals(tempUser.UserName)
                && u.UserPass.Equals(tempUser.UserPass) && u.UserEmail.Equals(tempUser.UserEmail)).FirstOrDefault();

                if (user != null)
                {
                    Session["user_name"] = user.UserName;
                    return RedirectToAction("DashBoard");
                }
                else
                {
                    ViewBag.LoginFailed = "User Not Found or Password Mismatched";
                    return View();
                }
            }
            return View();
        }



        public ActionResult DashBoard()
        {
            string name = Convert.ToString(Session["user_name"]);
            var user = db.JobFinders.Where(u => u.UserName.Equals(name)).FirstOrDefault();

            return View(user);
        }

        public ActionResult JobCircuit2(string search)
        {
            string name = Convert.ToString(Session["user_name"]);
            var user = db.JobFinders.Where(u => u.UserName.Equals(name)).FirstOrDefault();
            return View(db.JobPosters.Where(x => x.JobName.Contains(search) || x.JobDesc.Contains(search) || search == null).ToList());

        }

        public ActionResult DashBoard2()
        {
            return View(db.JobFinders.ToList());
        }



        // GET: JobFinders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobFinder jobFinder = db.JobFinders.Find(id);
            if (jobFinder == null)
            {
                return HttpNotFound();
            }
            return View(jobFinder);
        }

        // POST: JobFinders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            JobFinder jobFinder = db.JobFinders.Find(id);
            db.JobFinders.Remove(jobFinder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DevProject/Controllers/JobPostersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DevProject.Models;

namespace DevProject.Controllers
{
    public class JobPostersController : Controller
    {
        private DevProjectDbEntities db = new DevProjectDbEntities();

        // GET: JobPosters
        public ActionResult Index()
        {
            return View(db.JobPosters.ToList());
        }

        // GET: JobPosters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobPoster jobPoster = db.JobPosters.Find(id);
            if (jobPoster == null)
            {
                return HttpNotFound();
            }
            return View(jobPoster);
        }

        // GET: JobPosters/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: JobPosters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobPostID,UserName,UserPass,ConfirmPass,JobName,JobDesc,WorkDays,Salary,Skills,Age,Gender,Email,ConNumber")] JobPoster jobPoster)
        {
            if (ModelState.IsValid)
            {
                db.JobPosters.Add(jobPoster);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(jobPoster);
        }

        //public ActionResult ShowApplied()
        //{
            
        //    List<JobPoster> posternames = db.JobPosters.ToList();
        //    List<Apply> appliernames = db.Applies.ToList();

        //    var multipletable = from jpn in posternames
        //                        join an in appliernames on jpn.JobPostID equals an.JobPostID into table1
        //                        from an in table1.DefaultIfEmpty()
        //                        select new PosterApplyJoin { JobPosterName = jpn, AppliedName = an };
        //          return View(multipletable);
        //}


        // GET: JobPosters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobPoster jobPoster = db.JobPosters.Find(id);
            if (jobPoster == null)
            {
                return HttpNotFound();
            }
            return View(jobPoster);
        }

        // POST: JobPosters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobPostID,UserName,UserPass,JobName,JobDesc,WorkDays,Salary,Skills,Age,Gender,Email,ConNumber")] JobPoster jobPoster)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jobPoster).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(jobPoster);
        }

        //GET: Login

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(TempUser2 tempUser)
        {
            if (ModelState.IsValid)
            {
                var user = db.JobPosters.Where(u => u.UserName.Equals(tempUser.UserName)
                && u.UserPass.Equals(tempUser.UserPass) && u.Email.Equals(tempUser.Email)).FirstOrDefault();

                if (user != null)
                {
                    Session["user_name"] = user.UserName;
                    return RedirectToAction("DashBoard");
                }
                else
                {
                    ViewBag.LoginFailed = "User Not Found or Password Mismatched";
                    return View();
                }
            }
            return View();
        }

        public ActionResult DashBoard()
        {
            string name = Convert.ToString(Session["user_name"]);
            var user = db.JobPosters.Where(u => u.UserName.Equals(name)).FirstOrDefault();

            return View(user);
        }

        public ActionResult JobCircuit(string search)
        {
           
             
            return View(db.JobPosters.Where(x => x.JobName.Contains(search) || x.JobDesc.Contains(search)||search == null).ToList());
        }

        public ActionResult PosterSee()
        {
            var applies = db.Applies.Include(a => a.JobFinder).Include(a => a.JobPoster);
            return View(applies.ToList());
        }


        // GET: JobPosters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobPoster jobPoster = db.JobPosters.Find(id);
            if (jobPoster == null)
            {
                return HttpNotFound();
            }
            return View(jobPoster);
        }

        // POST: JobPosters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            JobPoster jobPoster = db.JobPosters.Find(id);
            db.JobPosters.Remove(jobPoster);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DevProject/Views/JobPosters/Delete.cshtml
@model DevProject.Models.JobPoster

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JobPoster</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserPass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserPass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkDays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkDays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Skills)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Skills)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DevProject/Views/JobPosters/Details.cshtml
@model DevProject.Models.JobPoster

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>JobPoster</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserPass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserPass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkDays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkDays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Skills)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Skills)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.JobPostID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DevProject/Views/JobPosters/JobCircuit.cshtml
@model IEnumerable<DevProject.Models.JobPoster>

@{
    ViewBag.Title = "JobCircuit";
    Layout = null;
}



<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Job Circuit Page</title>
    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/Content/vendors_admin/images/logo.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/vendors_admin/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/vendors_admin/images/favicon-16x16.png">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    @Styles.Render("~/Content2/vendor/bootstrap/css/bootstrap.min.css")
    @Styles.Render("~/Content2/vendor/bootstrap-icons/bootstrap-icons.css")
    @Styles.Render("~/Content2/cssassets/vendor/aos/aos.css")
    @Styles.Render("~/Content2/vendor/remixicon/remixicon.css")
    @Styles.Render("~/Content2/vendor/swiper/swiper-bundle.min.css")
    @Styles.Render("~/Content2/vendor/glightbox/css/glightbox.min.css")
    @Styles.Render("~/Content2/css/style.css")
    @Styles.Render("~/Content2/css/profprofile.css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

            <a href="#hero" class="logo d-flex align-items-center">
                <img src="~/Content/img/logo.png" alt="">
                <span style="color:chartreuse;">Job Finders</span>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto" href="https://localhost:44327/">Home</a></li>
                    <li><a class="nav-link scrollto" href="~/Universities/ShowAll">Find Jobs</a></li>
                    <li><a class="nav-link scrollto" href="~/Students/Index">Post Jobs</a></li>
                    <li><a class="nav-link scrollto" href="~/Home/Index/#contact">Contact</a></li>
                    <li><a class="nav-link scrollto" href="~/Home/Index/#team">About Us</a></li>
                    <li><a class="nav-link scrollto " style="margin-left:35px; " href="~/Professors/Profile/">My Profile</a></li>
                    
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
        </div>
    </header>

    <!-- Header -->
    <main>
        <section id="portfolio" class="portfolio">
            <div class="container" data-aos="fade-up">
                <header class="section-header">
                    <h2>Jobs</h2>
                    <p>Check out the latest Jobs</p>
                </header>
                <!-- Page content -->

                <div>
                    @using (Html.BeginForm("JobCircuit", "JobPosters", FormMethod.Get))
                    {
                        //@Html.TextBox("searching")<input type="submit" value="Search" />
                        @Html.TextBox("search", null, new { id = "choices-text-preset-values", @class = "form-control", @type = "text", @placeholder = "Type to search..." })<input type="submit" value="search" />
                    }
                </div>
                <br><br><br>
                @if (Model.Count() == 0)
                {
                    <p style="color:red"> No Match Found!</p>
                }
                else
                { 

            <div class="row gy-4 portfolio-container" data-aos="fade-up" data-aos-delay="200">
                @foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-6 portfolio-item">
                        <div class="portfolio-wrap">

                            <h3 style="text-align:center">@Html.DisplayFor(modelItem => item.JobName) </h3>
                            <p>@Html.DisplayFor(modelItem => item.Skills)</p>
                            <p> @Html.DisplayFor(modelItem => item.Salary)</p>
                            <p>  @Html.DisplayFor(modelItem => item.JobDesc)</p>
                            <p> @Html.DisplayFor(modelItem => item.Email)</p>
                            <div class="portfolio-info">
                                @*<button class="btn btn--radius-2 btn--blue" onclick="~/JobFinders/Create" >You need to be logged in to apply</button>*@
                                <a class="nav-link scrollto" href="~/JobFinders/Create">You need to be logged in to apply</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
                  }

                
</section>
    </main>


    <!-- Vendor JS Files -->
    @Scripts.Render("~/assets2/vendor/bootstrap/js/bootstrap.bundle.js")
    @Scripts.Render("~/assets2/vendor/aos/aos.js")
    @Scripts.Render("~/assets2/vendor/php-email-form/validate.js")
    @Scripts.Render("~/assets2/vendor/swiper/swiper-bundle.min.js")
    @Scripts.Render("~/assets2/vendor/purecounter/purecounter.js")
    @Scripts.Render("~/assets2/vendor/isotope-layout/isotope.pkgd.min.js")
    @Scripts.Render("~/assets2/vendor/glightbox/js/glightbox.min.js")


    <!-- Template Main JS File -->
    @Scripts.Render("~/assets2/js/main.js")
    @*@RenderSection("scripts", required: false)*@
</body>
</html>


@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserPass)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WorkDays)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Skills)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ConNumber)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserPass)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WorkDays)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Skills)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ConNumber)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.JobPostID }) |
                @Html.ActionLink("Details", "Details", new { id=item.JobPostID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.JobPostID })
            </td>
        </tr>
    }

    </table>*@

DevProject/Views/JobPosters/PosterSee.cshtml
@model IEnumerable<DevProject.Models.Apply>

@{
    ViewBag.Title = "PosterSee";
}

<h2>People who Have Applied For Jobs</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ApplyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobFinder.UserEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobPoster.JobName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ApplyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobFinder.UserEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobPoster.JobName)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id=item.ApplyID }) |*@

                @*@Html.ActionLink("Delete", "Delete", new { id=item.ApplyID })*@
            </td>
        </tr>
    }

</table>
@Html.ActionLink("Check Out Finder Profiles", "DashBoard2", "JobFinders") |

DevProject/Views/JobPosters/ShowApplied.cshtml
@model IEnumerable<DevProject.Models.PosterApplyJoin>
@{
    ViewBag.Title = "ShowApplied";
}


<center>
    <h2>ShowApplied</h2>
    <hr/>
    <table class="table">
        <tr>
            <td>Job Posters Name</td>
            <td>Job Appliers Name</td>
        </tr>
        @foreach(var item in Model)
            {
                <tr>
                    <td>@item.JobPosterName</td>
                    <td>@item.AppliedName</td>

                </tr>
            }
    </table>

</center>